### ISSUE TITLE
Build problem with icu

### ISSUE THREAD

**Issue by aptakhin** [Altinity/homebrew-clickhouse#17]
Got problems installing `altinity/clickhouse`. Both versions `21.11`, `21.12` failed with same error with icu submodule. Output of build attached in files and included environment below. Haven't looked in altinity brew build instruction yet.

Last lines of build, full version included in files below.

```bash
Submodule path 'contrib/xz': checked out '869b9d1b4edd6df07f819d360d306251f8147353'
Submodule path 'contrib/yaml-cpp': checked out '0c86adac6d117ee2b4afcedb8ade19036ca0327d'
Submodule path 'contrib/zlib-ng': checked out '6a5e93b9007782115f7f7e5235dedc81c4f1facb'
Submodule path 'contrib/zstd': checked out 'a488ba114ec17ea1054b9057c26a046fc122b3b6'
Unable to checkout 'faa2f9f9e1fe74c5ed00eba371d2830134cdbea1' in submodule path 'contrib/icu'
```

[brew-install-ch21.11.txt](https://github.com/Altinity/homebrew-clickhouse/files/7734560/brew-install-ch21.11.txt)

[brew-install-ch21.12.txt](https://github.com/Altinity/homebrew-clickhouse/files/7734561/brew-install-ch21.12.txt)

```bash
MacOS Catalina 10.15.7 (19H2)
2,6 GHz 6-Core Intel Core i7

% brew --env
HOMEBREW_CC: clang
HOMEBREW_CXX: clang++

MAKEFLAGS: -j12
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.15
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/bin:/bin:/usr/sbin:/sbin

% clang --version
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

**Comment by traceon** [comment]
Try running this first:
https://github.com/Altinity/homebrew-clickhouse/blob/dd7a5d37a93dfd0c6512ea671afec29a03491ed6/.github/workflows/tests.yml#L44-L46

**Comment by traceon** [comment]
Feel free to reopen, if that didn't solve your problem.

**Comment by alexey-milovidov** [comment]
You can download the official build for Mac as follows:
```
curl https://clickhouse.com/ | sh
```

**Comment by aptakhin** [comment]
Sorry, I didn't react somehow here because of a very difficult December that year and the advice above didn't help a lot. And didn't write my solution here because in December 2021 I see clickhouse.com provides pretty new version, so yes I solved the problem exactly this way. 

Thank you, guys, a lot!

> You can download the official build for Mac as follows:
> 
> ```
> curl https://clickhouse.com/ | sh
> ```
