### ISSUE TITLE
Crazy resource consumption after idling too long?

### ISSUE THREAD

**Issue by dbackeus** [Altinity/homebrew-clickhouse#29]
Hi,

I have been using the latest ClickHouse (22.1.2.2) using this formula via `brew services` on my brand new MacBook Pro M1 16" for about a week. I've noticed that after clickhouse has been running for some number of hours (10-20 hours anecdotally) I find that it has entered a state where it is using ~400% CPU. When in this state and I connect via `clickhouse client` I get the following error:

```
Cannot load data for command line suggestions: 
Code: 241. DB::Exception: Received from localhost:9000. 
DB::Exception: Memory limit (total) exceeded: would use 19.06 TiB 
(attempt to allocate chunk of 4430630 bytes), maximum: 14.40 GiB. (MEMORY_LIMIT_EXCEEDED) 
(version 22.1.2.1-stable)
```

The number of "would use" memory is always some absurdly high number of TB.

I saw this happen even after a brand new install without having created a database as of yet. Currently I have a fairly modest database with a few GB of data and I've hardly made queries against it at all. It's idling 99% of the time except for when I play around with some queries to measure performance.

When the issue occurs running `brew services restart clickhouse` seems to resolve it.

Note that I frequently put the laptop to sleep by closing the lid so one angle is that maybe something goes wrong due to hibernation.

Let me know if there is anything I can do to provide more details to help debug this issue.

**Comment by traceon** [comment]
Could you please try the latest version 22.2 formula and see if it persists?

**Comment by dbackeus** [comment]
Yes I'll try that 👍 

I ran into some minor issues while upgrading reported here https://github.com/Altinity/homebrew-clickhouse/issues/37

**Comment by dbackeus** [comment]
Can confirm the issue remains with the latest 22.2 release. Currently at ~380% CPU after starting it yesterday (without actually making any inserts or queries).

<img width="554" alt="Screenshot 2022-03-15 at 09 12 53" src="https://user-images.githubusercontent.com/3461/158334100-05433992-1ff1-4b90-aab7-824f9b04ef31.png">

Clickhouse clients produces the follow error:

```
$ clickhouse client

ClickHouse client version 22.2.3.1.
Connecting to localhost:9000 as user default.
Connected to ClickHouse server version 22.2.3 revision 54455.

davidbakeussmbp :) Cannot load data for command line suggestions: Code: 241. DB::Exception: Received from localhost:9000. DB::Exception: Memory limit (total) exceeded: would use 8.93 TiB (attempt to allocate chunk of 4431462 bytes), maximum: 14.40 GiB. (MEMORY_LIMIT_EXCEEDED) (version 22.2.3.1)
```

**Comment by traceon** [comment]
Thanks, this needs deeper investigations...

**Comment by traceon** [comment]
Hi @dbackeus, if this is still relevant, could you please check the latest formula version (22.6) and see if it is fixed there?

**Comment by bojdell** [comment]
I have the same issue running on Macbook Pro M1 14" 16GB RAM. The CPU usage is less of an issue for me but the memory estimation/sizing for queries is way off (in the TBs as well for me). I was previously was able to workaround this by restarting clickhouse-server, however after the latest brew update to 22.6 this workaround no longer works and my local development is blocked. Trying to downgrade locally ATM but hard to do with brew and there are issues:
```
$ brew services start clickhouse@lts
Bootstrap failed: 5: Input/output error
Try re-running the command as root for richer errors.
Error: Failure while executing; `/bin/launchctl bootstrap gui/501 /Users/bo/Library/LaunchAgents/homebrew.mxcl.clickhouse@22.3.plist` exited with 5.
```
Running as root didn't uncover anything useful.

I posted some more details here, may migrate it to separate issue: https://github.com/ClickHouse/ClickHouse/issues/7207#issuecomment-1186012046

**Comment by bojdell** [comment]
Ah, so I was able to resolve the brew services issue by running ClickHouse in the foreground and viewing the log:
```
/opt/homebrew/opt/clickhouse@22.3/bin/clickhouse server --config-file /opt/homebrew/etc/clickhouse-server/config.xml --pid-file /opt/homebrew/var/run/clickhouse-server/clickhouse-server.pid
...
2022.07.18 11:10:00.492740 [ 45448 ] {} <Error> Application: DB::Exception: A setting 'max_threads' appeared at top level in config /opt/homebrew/etc/clickhouse-server/config.xml. But it is user-level setting that should be located in users.xml inside <profiles> section for specific profile. You can add it to <profiles><default> if you want to change default value of this setting. You can also disable the check - specify <skip_check_for_incorrect_settings>1</skip_check_for_incorrect_settings> in the main configuration file.
2022.07.18 11:10:00.492771 [ 45448 ] {} <Information> Application: shutting down
```
Turns out I had some config settings in the wrong places when trying to tune to avoid the MEMORY_LIMIT_EXCEEDED issue  - after cleaning these up ClickHouse starts properly at any version (tried 22.2 and 22.6). I will try to use 22.6 again and see if the settings will avoid MEMORY_LIMIT_EXCEEDED or if I can at least keep using my workaround of restarting the server.

**Comment by dbackeus** [comment]
For the record: Just back from vacation and have upgraded to 22.6. Will monitor the service for CPU usage bloat. If the issue is still present it should occur within a day or so based on past experience.

**Comment by traceon** [comment]
@dbackeus thanks, keep us posted. BTW, just added 22.7 formula.

**Comment by dbackeus** [comment]
Four days later and no CPU issues seen with 22.6.

Just upgraded to 22.7, will run it for a few days as well just to be sure 🤞

**Comment by dbackeus** [comment]
22.7 has been running for two days now without CPU problems. I'll close the issue 🥳 

If the RAM issues are still a problem perhaps @bojdell could open up a new issue focusing on that.
