### ISSUE TITLE
Latest Clickhouse?

### ISSUE THREAD

**Issue by alanpaulkwan** [Altinity/homebrew-clickhouse#42]
Dear Altinity

I love what you guys are doing - any possibility of upgrading to 22.6? I have tried the Docker but it seems to consume my battery much more than native Clickhouse

**Comment by traceon** [comment]
22.6 has been added (and is the default version as of now).

**Comment by alexey-milovidov** [comment]
@alanpaulkwan You can download the latest ClickHouse release for Mac as follows:
```
curl https://clickhouse.com/ | sh
```
